# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 30
command_timeout = 500

format = """\
$username\
$hostname\
${custom.fig}\
$directory\
$cmd_duration\
$time\
$env_var\
$line_break\
$character"""

[directory]
truncation_length = 4
truncate_to_repo = false
# style = "bold blue"

[time]
disabled = false
use_12hr = false
utc_time_offset = "local"
style = "yellow"

[custom.g3]
when = """ [[ "$PWD" =~ "/google/src/cloud/$USER" ]] """
style = "white"
symbol = "GG"
format = "[${symbol}]($style)"

[custom.fig]
command = """ echo "${${PWD}#/google/src/cloud/${USER}/}" | cut -d '/' -f 1 """
when = """ [[ "$PWD" =~ "/google/src/cloud/$USER" ]] """
style = "bold cyan"
format = "[🌱($output) ]($style)"
